# development configuration
---
spring:
  config:
    active:
      on-profile: "dev"
server:
  email: dev@mkyong.com
  cluster:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: postgres
    password: postgres
test:
  bo:
    url: https://test-jx-dev.jx3.company.uk
  account:
    name: 'test-dev'
