name: Check
on: [push]
jobs:
  download-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get permissions
        run: git update-index --chmod=+x mvnw
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: yuzhiyongcn/setup-maven@v1.0.0
        with:
          maven-version: 3.8.2
      - name: Check Maven wrapper version
        run: mvn -v
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
