name: Spring Boot automated tests

on: [ push ]

env:
  CLIENT_USER_NAME: Buzz McCallister

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check build
        run: echo "Build was checked."
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Java version
        run: java -version
      - name: Check current dir
        run: |
          pwd
          echo "Check list directory contents of files and directories"
          ls -la
          echo "Check env variables in workflow"
          echo "The workflow uses CLIENT_USER_NAME = $CLIENT_USER_NAME"
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: java -version
      - name: Run automated tests
        run: mvn test -Denv=prod
      - name: Print repository secrets
        run: |
          echo "Repository secret SECURITY_TOKEN = ${{ secrets.SECURITY_TOKEN }}"
          export SEC_TOKEN = ${{ secrets.SECURITY_TOKEN }}
          echo "$SEC_TOKEN"
