name: Spring Boot automated tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Maven version
        run: mvn -v
      - name: Check Java version
        run: java -version
      - name: Check current dir
        run: pwd
      - name: Check list directory contents of files and directories
        run: ls -la
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - run: java -version
