name: Run Spring Boot automated tests

on: [ push ]
#on:
#  workflow_dispatch:
#  pull_request:
#    types: [ opened, edited, reopened ]
#on:
#  push:
#    branches:
#      - main

env:
  CLIENT_USER_NAME: Buzz McCallister
  SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}
  SECURITY_NAME: ${{ vars.SECURITY_NAME }}
  DEPLOYMENT_TOKEN: 1234

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check build
        run: echo "Build was checked."
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Java version
        run: java -version
      - name: Check current dir
        run: |
          pwd
          echo "Check list directory contents of files and directories"
          ls -la
          echo "Check env variables in workflow"
          echo "The workflow uses CLIENT_USER_NAME = $CLIENT_USER_NAME"
          echo "My deployment token is $DEPLOYMENT_TOKEN"
      - name: Print repository secrets
        run: |
          echo "Repository secret SECURITY_TOKEN = $SECURITY_TOKEN"
          echo "SECURITY_NAME = $SECURITY_NAME"
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: java -version
      - name: Run automated tests
        run: mvn test -Denv=prod
      - name: Upload surefire-report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report-files
          path: target/surefire-reports/*.txt
  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Get surefire-report
        uses: actions/download-artifact@v4
        with:
          name: surefire-report-files
      - name: Display structure of downloaded files
        run: ls -R
